// reconstruct/notfound_log.cpp
#include "reconstruct/notfound_log.hpp"

#include <fstream>
#include <sstream>

#include "concolic/concolic.hpp"

namespace lure::reconstruct {

bool write_notfound_log(const std::string& path, const std::vector<NotfoundEntry>& entries, std::string& err)
{
    std::ofstream f(path);
    if (!f)
    {
        err = "cannot open report file: " + path;
        return false;
    }
    f << "; lure not-found report\n";
    f << "; " << entries.size() << " value(s) reconstructed but not observed\n\n";
    for (const NotfoundEntry& e : entries)
        f << "line " << e.lua_line << " (" << e.where << "): " << e.reason << "\n";
    f << "\n; generated by lure; do not edit\n";
    return static_cast<bool>(f);
}

bool append_feasibility_log(const std::string& path, const std::vector<lure::concolic::Feasibility>& feas,
    std::string& err)
{
    std::ofstream f(path, std::ios::app);
    if (!f)
    {
        err = "cannot open report file for append: " + path;
        return false;
    }
    f << "\n; layer 4: feasibility of unexecuted branch sides (path-prefix concolic check)\n";
    if (feas.empty())
    {
        f << "; no unexecuted branch side was probed (no decidable branch with a declared other target)\n";
        return static_cast<bool>(f);
    }
    for (const lure::concolic::Feasibility& x : feas)
    {
        const char* v = "unknown";
        if (x.result.verdict == lure::concolic::Verdict::Sat)
            v = "sat";
        else if (x.result.verdict == lure::concolic::Verdict::Unsat)
            v = "unsat";
        f << "branch pc " << x.branch_pc << " -> other side pc " << x.other_target << " (" << x.condition
          << "): " << v;
        if (!x.result.model.empty())
            f << " (model: " << x.result.model << ")";
        if (!x.result.note.empty())
            f << " [" << x.result.note << "]";
        f << "\n";
    }
    return static_cast<bool>(f);
}

} // namespace lure::reconstruct